name: farma_friend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.0  
  firebase_analytics: ^11.3.3
  google_fonts: ^6.2.1  # Upgrade to the latest version if possible
  carousel_slider: ^5.0.0
  page_transition: ^2.1.0
  animated_splash_screen: ^1.3.0
  path: ^1.9.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  sqflite: ^2.3.3+2
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  multicast_dns: ^0.3.2+7
  mqtt_client: ^10.5.1
  flutter_ai_toolkit: ^0.6.0
  google_generative_ai: ^0.4.6

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1    
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_transparent.png"  
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/farmer_main.jpg 
    - assets/crop_rotation.png
    - assets/iot_sensor.png
    - assets/soil_test.jpg
    - assets/main_page.jpg
    - assets/create_page.jpg
    - assets/crop.jpg
    - assets/default_profile.jpg
    - assets/background.jpg